import 'package:flutter/material.dart';
import './models/category.dart';
import './models/meal.dart';

const dummyCategory = [
  Category(
    id: 'c1',
    title: 'French Cuisine',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Chinese Cuisine',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Japanese Cuisine',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Indian Cuisine',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Italian Cuisine',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Greek Cuisine',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Spanish Cuisine',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Mediterranean Cuisine',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'Lebanese Cuisine',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Moroccan Cuisine',
    color: Colors.teal,
  ),
];

const dummyMeals = [
  Meal(
    id: 'm1',
    categories: [
      'c1',
    ],
    title: 'Potatoes Dauphinoise',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://www.oliviascuisine.com/wp-content/uploads/2016/07/Christmas-Sides-590.jpg',
    duration: 20,
    ingredients: [
      ' 1 1/2 cups cream , full fat (Note 1)',
      ' 2 garlic cloves , minced',
      ' 30g / 2 tbsp unsalted butter , melted',
      ' 1.25 kg / 2.5 lb starchy potatoes , Russet, Sebago, Maris Piper (Note 2)',
      ' 1 tsp salt',
      ' 1/4 tsp pepper',
      ' 2 1/2 cups gruyere cheese (or mozzarella) , freshly grated yourself (Note 3)',
      '  2 tsp thyme leaves , fresh (optional – but highly recommended)',
    ],
    instructions: [
      ' Cream Mixture: Place butter, cream and garlic in a jug. Mix until combined.',
      'Preheat oven to 180°C/350°F.',
      'Slice potatoes: Peel the potatoes and slice them 1/8"/3 mm thick. Or use a slicer!',
      'Layer 1: Spread 1/3 of the potatoes in a baking dish (Note 3), then pour over 1/3 of the Cream Mixture, scatter with 1/3 of the salt, pepper and thyme. Sprinkle with 3/4 cups cheese.',
      'Layers 2 & 3: Repeat for the 2nd and third layer, but do not finish with cheese on the top layer (will add later).',
      'Cover & bake: Cover with lid or foil, and bake for 1 hr 15 min or until the potatoes in the middle are soft (use knife to test).',
      'Top with cheese, bake again: Remove foil, top with cheese. Bake for a further 10 to 15 minutes until golden and bubbly. Stand 5 minutes before serving.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c1',
    ],
    title: 'Quiche Lorraine',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://www.recipetineats.com/wp-content/uploads/2014/12/Hash-Brown-Crust-Quiche-Lorraine-11.jpg?resize=650,906',
    duration: 10,
    ingredients: [
      ' 1.2 lb / 600g starchy potatoes (Note 1) OR 4 cups (not packed) frozen shredded hash browns, thawed',
      ' 1 2 tbsp unsalted butter , melted',
      ' 1 tsp salt',
      ' Butter , for greasing',
      ' Oil spray (or olive oil)',
      ' 2 egg yolks',
      ' 2 eggs',
      ' 1 cup milk (preferably full cream, but low fat will also work)',
      ' 3/4 cup cream',
      ' Pinch of freshly grated nutmeg (optional)',
      ' 1/2 tsp salt',
      ' Black pepper',
      ' 1/2 tbsp butter',
      ' 6 oz / 180g bacon , cut into large dice (about 1cm x 0.5cm / 2/3" x 1/5")',
      ' 1 small onion , diced (or half a large onion)',
      ' 1 garlic clove , minced',
      ' 3/4 cup grated cheese (tasty, cheddar or gruyere)'
    ],
    instructions: [
      'Preheat oven to 425F/220C with the oven shelf in the top 1/3 of the oven.',
      'Grease a 9"/ 23cm pie dish (Note 2)',
      '\n\nHash Brown Crust',
      '\nIf shredding potatoes yourself, peel and grate the potatoes. Place the shredded potatoes into a colander and rinse for 10 seconds, using your hands to move the grated potatoes around, until the water runs clear.',
      'Take a handful of the rinsed grated potatoes OR the thawed frozen shredded hash browns and squeeze the excess water out, then place into a large bowl. Repeat with remaining potato. You should have about 4 cups of shredded potato.',
      'Add melted butter and salt and mix to combine.',
      'Pour the shredded potato into the pie dish. Use a large dessert spoon to spread the hash browns over the base and side of the pie dish.',
      'Use your hands or a spatula to pat down the base of the hash brown crust so it is fairly firmly packed.',
      'Spray the hash brown crust with oil spray (I used olive oil spray).',
      'Bake the crust for 30 minutes.',
      '\n\nPrepare Filling & Egg Mixture',
      '\nWhile the crust is baking, melt 1/2 tbsp butter in a fry pan over medium high heat.',
      'Add onion, garlic and bacon into the fry pan. Saute until the onion is translucent and the bacon is just starting to brown (but not crisp).',
      'Remove from the stove and set aside to cool slightly.',
      'Place Egg Mixture ingredients in a bowl and whisk to combine.',
      '\n\nFill Quiche',
      '\nWhen the crust is light golden brown on the surface of the base and golden brown on the walls of the crust (around 30 minutes), remove from the oven.',
      'Scatter the bacon onion mixture across the base, then the cheese.',
      'Then pour the Egg Mixture in.',
      '\n\nBaking the Quiche',
      '\nReturn the quiche to the oven and turn the oven down to 180C/350F.',
      'Bake for 25 minutes, or until the Filling is set. Test this either by inserting a skewer into the centre (it should come out clean) or by touching the centre gently (it should spring back).'
          'Let it rest for 5 to 10 minutes before serving.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c1',
    ],
    title: 'Croque Madame',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Simple,
    imageUrl:
    'https://showmetheyummy.com/wp-content/uploads/2015/03/Croque-Madame-Final-Whole4.jpg',
    duration: 45,
    ingredients: [
      'Béchamel Sauce – a classic creamy white sauce.',
      'Butter – makes the sauce ultra-creamy.',
      'Flour – combines with the butter to create a “roux” which thickens the sauce.',
      '1Salt – brings out the flavor of the other ingredients.',
      'Nutmeg – adds a nice, nutty sweetness. A little pinch goes a long way. This is often the secret ingredient to a white sauce.',
      'Milk – the base of the sauce',
      'Parmesan Cheese – adds a salty, sharp flavor to offset the creaminess. It’s also used as an additional topping for the sandwich.',
      'Brioche – a soft, buttery, and subtly sweet bread that’s toasted to perfection.',
      'Gruyere Cheese – a creamy and nutty cheese that melts into ooey, gooey, deliciousness.',
      'Ham – adds a nice, smoky flavor to the sandwich.',
      'Butter – buttering the bread before cooking creates that crunchy, golden-brown texture and color.',
      'Eggs – fried to perfection to finish off the sandwich.',
    ],
    instructions: [
      'Use a whisk to mix the ingredients for your béchamel sauce in a saucepan.',
      'Cut the brioche and layer a slice with cheese, ham, and sauce. Top it off with another brioche slice.',
      'Cook in a large nonstick pan. Remove and place on a baking sheet lined with a silicone mat.',
      'Top with another layer of béchamel and parmesan and cook in the oven while you fry an egg.',
      'Remove sandwich from the oven, top with your fried egg, and devour!'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c1',
    ],
    title: 'Croissants',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://www.monpetitfour.com/wp-content/uploads/2015/04/croissants-1-copy.jpg',
    duration: 60,
    ingredients: [
      'for the dough',
      '1 lb . 2 oz. unbleached all-purpose flour; more for rolling (4 cups)',
      '5 oz . cold water (1/2 cup + 2 Tbs.)',
      '5 oz . cold whole milk, (1/2 cup + 2 Tbs.)',
      '2 oz . granulated sugar (1/4 cup + 2 Tbs.)',
      '1 1/2 oz . soft unsalted butter (3 Tbs.)',
      '1 Tbs . + scant 1/2 tsp. active dry yeast',
      '2 1/4 tsp . table salt',
      '\nfor the butter layer',
      '10 oz . unsalted butter (1 1/4 cups)',
      '\nfor the egg wash',
      '1 egg, beaten',
    ],
    instructions: [
      '\n\nPart 1 - Create Your Dough',
      'In a large bowl, combine all of the dough ingredients together, including the flour, cold water, cold milk, granulated sugar, unsalted butter, yeast, and table salt. Mix everything together with a wooden spoon; then knead for a couple of minutes into a smooth ball.',
      'Lightly flour a baking pan before transferring your dough ball into the pan. Lightly dust the top of the dough with flour before covering with plastic wrap. Refrigerate overnight (or at least 8 hours). ',
      'Take the cold unsalted butter appropriated for your butter layer and cut it into 1/2 inch thick slices. Arrange the slices, side-by-side, on a sheet of parchment paper to form a 6 inch square. Cut any butter slices in half or diagonally if needed to create this 6 inch size square.',
      'Place another sheet of parchment paper on top of the butter and use your rolling pin to slightly pound out the butter. Use your pin to roll north-south and east-west to make the butter layer thinner while equally elongating all sides of the square. You’ll want to end up with a square that is about 7 1/2 inches long. Temporarily place your butter in the fridge to remain cold.',
      'Dust your work surface with flour. Then, take out your dough that had been refrigerated overnight. Roll the dough out into a 10 inch square. Place your butter layer on top of this dough square so that the pointed ends of the butter face the sides of the dough square. The butter should look like a diamond shape on the dough.',
      'Now, fold the corners of the dough in towards the center so that all the dough corners meet. Pinch the dough together along all its edges so that the butter is safely enveloped inside, with no chance of seeping out. \nUse your rolling pin to create long strokes and elongate the dough. You’ll want to create a long strip of dough that is about 8 inches in width and 24 inches in length. The first time you’re rolling, your dough will probably be wider than 8 inches - thats OK. If you see your dough is beginning to widen too much, simply lift the dough from its center to shorten its width. If the dough is sticky, lightly dust with a bit of flour. Once your dough has achieved 24 inches in length, fold one end of the dough into the center (like a pamphlet or brochure). Use a pastry brush to dust off any residual flour from the dough. Place the folded dough onto a baking sheet that’s been dusted with flour and cover tightly with plastic wrap. Place in the freezer for 20 minutes.',
      'Repeat the previous step 2 more times, always rolling the dough with the open ends of the folded dough facing you. You will notice it getting more difficult to roll the dough out to 24 inches long - again, this is OK; continue rolling it out as close to 24 inches as you can get. After the third time that you’ve rolled and folded the dough, instead of placing the dough in the freezer, place the plastic-wrapped dough in the fridge to chill overnight (or at least 8 hours). ',
      'Dust your work surface with flour. Use your rolling pin to create light, quick strokes as you elongate your dough in a long rectangle. Make sure the open ends of the folded dough are facing you. This time, you’ll want to create a strip of dough that is about 8 inches wide and close to 44 inches long. Again, if you see your dough widening too much, pick up the dough from its center to shorten its width. Shape both ends of your rectangle into neat edges as best as possible. \nUse a bench scraper, sharp knife, or pizza cutter to slice off the uneven ends of your rectangle (about 1/2” to 1” off each end). Use a ruler to go along the top length of your rectangle to measure and mark a point every 5 inches along the top. \nThen, take your ruler along the bottom length of the rectangle and position it 2 1/2 inches in. Mark this point. From this point, measure and mark every 5 inches on. Now, take your knife and position it at the first point along the top length of the dough. Slice diagonally, downwards to the right, to the closest point on the bottom length of the dough. Repeat this move for the rest of the points along the top length of the dough. Once you reach the end, repeat this step moving towards the left this time around. You should end up with 15 triangles. \nLift each triangle up from its base (the shortest side of the triangle), and use your other hand to gently pull its pointed end in the opposite direction. You want to essentially elongate and stretch the triangle just a bit. Now, place the triangle back down on your work surface, with its base sitting closest to you. Use your knife to make a 1/2 inch notch (or cut) right in the center of the base. Grab hold of each side of the notch and gently roll the triangle away from you, towards the pointed end, flaring your hands outward. \nPlace the shaped croissants on baking sheets fitted with parchment paper. Brush the croissants with egg wash before loosely covering the croissants with plastic wrap; place in a warm, draft-free area for about 2 hours to proof. They’re ready to bake when the croissants have expanded in size and their many layers become apparent. \nPreheat the oven to 425°F, placing your top rack on the highest position in the oven, and your bottom rack on the lowest position in the oven. Very delicately brush the egg wash over all the croissants again. Place one of the baking sheets in the oven on the top rack for 10 minutes. Then move the sheet to the bottom rack and bake for another 5 to 6 minutes, or until deep golden brown. Remove from the oven and let croissants slightly cool on wire rack. Bake the remaining croissants in the same manner. ',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2',
    ],
    title: 'Dim Sums',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
    'https://i.ndtvimg.com/i/2015-10/dimsum_625x350_51446202982.jpg',
    duration: 15,
    ingredients: [
      '\nFor chicken and prawn dumplings:',
      '150 gms chicken',
      '150 gms prawn',
      '5 gms sugar',
      '5 ml sesame oil',
      '2.5 gms white pepper',
      'Wonton skin',
      'Potato starch',
      'Salt',
      '\nFor vegetable coriander dumplings:',
      '10 gms carrots',
      '10 gms button mushrooms',
      '10 gms water chestnuts',
      '10 gms bamboo shoots',
      '10 gms garlic',
      '10 ml oil',
      '10 gms brown garlic',
      '5 gms sugar',
      '5 gms sesame oil',
      '\nFor wonton skin:',
      'Potato starch',
      'Salt',
      '50 gms wheat starch',
    ],
    instructions: [
      'Mince chicken and prawns and mix with sugar, salt, sesame oil and potato starch. Stuff the mixture in the wanton skin and steam.\n Serve with Diamond & soya Sauce',
      'Mix all ingredients except for wanton skin. Stuff the mixture in the wanton skin and steam. \n Serve with diamond sauce.',
      'Add cold water with potato and 50 gm of wheat starch, and mix with a pinch of salt.',
      'Add hot water to the mixture and stir till it thickens. Add potato starch till it gets tight.',
      'Make a roll and cut into small balls adding wheat starch over the ball.',
      'Then roll the balls in a flat and round shape with a roller and add fillings',
      'Soak 250 gm red chilies for 3 hours. Make into paste. Fry 100 gm garlic in oil.',
      'When garlic gets brown, add chili paste, salt, sugar and soya bean powder.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c2',
    ],
    title: 'East West Spring Rolls',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
    'https://c.ndtvimg.com/spring-rolls_625x300_1528971022214.jpg',
    duration: 240,
    ingredients: [
      '1 1/2 tsp Olive oil',
      '2 small Spring onion bulbs',
      '1 Green bell pepper, chopped',
      '4 pieces Tomatoes (sun dried)',
      '2 tbsp Bread crumbs',
      '1 1/2 tbsp Parmesan cheese',
      '1/2 tbsp Ginger, grated',
      '1 tsp Chives',
      '60 gram Buffalo mozzarella cheese',
      '1 tsp Balsamic vinegar',
      '2 tbsp Corn flour',
      '1 tsp Stock',
    ],
    instructions: [
      'In a hot pan add a dash of olive oil in which you can add the spring onions, green bell peppers and ginger.',
      'Give it a good toss.',
      'Add balsamic vinegar to deglaze and put in another bowl.',
      'Blend the sun dried tomatoes with breadcrumbs, Parmesan cheese and salt and pepper to taste.',
      "Add some chopped chives and give it a nice mix, don'\t need to make it too smooth.",
      'Mix with the spring onions and bell peppers.',
      'In a small bowl make a paste with 2 tbsp corn flour and 1 tsp stock.',
      'Brush a spring roll sheet with the corn flour paste.',
      'Put a few basil leaves. Top them with the mozzarella and tomato mix.',
      'Roll the spring roll into long cylindrical shape.',
      'Using cornstarch and stock as a binding agent.',
      'Deep fry till golden brown and serve with the basil dip.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2',
    ],
    title: 'Dim Sums',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
    'https://i.ndtvimg.com/i/2015-10/dimsum_625x350_51446202982.jpg',
    duration: 15,
    ingredients: [
      '\nFor chicken and prawn dumplings:',
      '150 gms chicken',
      '150 gms prawn',
      '5 gms sugar',
      '5 ml sesame oil',
      '2.5 gms white pepper',
      'Wonton skin',
      'Potato starch',
      'Salt',
      '\nFor vegetable coriander dumplings:',
      '10 gms carrots',
      '10 gms button mushrooms',
      '10 gms water chestnuts',
      '10 gms bamboo shoots',
      '10 gms garlic',
      '10 ml oil',
      '10 gms brown garlic',
      '5 gms sugar',
      '5 gms sesame oil',
      '\nFor wonton skin:',
      'Potato starch',
      'Salt',
      '50 gms wheat starch',
    ],
    instructions: [
      'Mince chicken and prawns and mix with sugar, salt, sesame oil and potato starch. Stuff the mixture in the wanton skin and steam.\n Serve with Diamond & soya Sauce',
      'Mix all ingredients except for wanton skin. Stuff the mixture in the wanton skin and steam. \n Serve with diamond sauce.',
      'Add cold water with potato and 50 gm of wheat starch, and mix with a pinch of salt.',
      'Add hot water to the mixture and stir till it thickens. Add potato starch till it gets tight.',
      'Make a roll and cut into small balls adding wheat starch over the ball.',
      'Then roll the balls in a flat and round shape with a roller and add fillings',
      'Soak 250 gm red chilies for 3 hours. Make into paste. Fry 100 gm garlic in oil.',
      'When garlic gets brown, add chili paste, salt, sugar and soya bean powder.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c2',
    ],
    title: 'East West Spring Rolls',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
    'https://c.ndtvimg.com/spring-rolls_625x300_1528971022214.jpg',
    duration: 240,
    ingredients: [
      '1 1/2 tsp Olive oil',
      '2 small Spring onion bulbs',
      '1 Green bell pepper, chopped',
      '4 pieces Tomatoes (sun dried)',
      '2 tbsp Bread crumbs',
      '1 1/2 tbsp Parmesan cheese',
      '1/2 tbsp Ginger, grated',
      '1 tsp Chives',
      '60 gram Buffalo mozzarella cheese',
      '1 tsp Balsamic vinegar',
      '2 tbsp Corn flour',
      '1 tsp Stock',
    ],
    instructions: [
      'In a hot pan add a dash of olive oil in which you can add the spring onions, green bell peppers and ginger.',
      'Give it a good toss.',
      'Add balsamic vinegar to deglaze and put in another bowl.',
      'Blend the sun dried tomatoes with breadcrumbs, Parmesan cheese and salt and pepper to taste.',
      "Add some chopped chives and give it a nice mix, don'\t need to make it too smooth.",
      'Mix with the spring onions and bell peppers.',
      'In a small bowl make a paste with 2 tbsp corn flour and 1 tsp stock.',
      'Brush a spring roll sheet with the corn flour paste.',
      'Put a few basil leaves. Top them with the mozzarella and tomato mix.',
      'Roll the spring roll into long cylindrical shape.',
      'Using cornstarch and stock as a binding agent.',
      'Deep fry till golden brown and serve with the basil dip.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c3',
    ],
    title: 'Sushi ',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://smedia2.intoday.in/indiatoday/images/stories/2015JUNE/sushiall_062415055231.jpg',
    duration: 20,
    ingredients: [
      '6 sheets sushi seaweed aka nori',
      '1 batch prepared sushi rice',
      '1/2 lb sushi-grade raw salmon or desired raw fish of choice',
      '4 oz cream cheese sliced into strips',
      '1 avocado sliced',
      'soy sauce for serving',
    ],
    instructions: [
      'Place the seaweed on a bamboo mat, then cover the sheet of seaweed with an even layer of prepared sushi rice. Smooth gently with the rice paddle.',
      'Layer salmon, cream cheese, and avocado on the rice, and roll it up tightly. Slice with a sharp knife, and enjoy with soy sauce.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c3',
    ],
    title: 'Yakitori  ',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://smedia2.intoday.in/indiatoday/images/stories/2015JUNE/yakitori-_062415055231.jpg',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c3',
    ],
    title: 'Tempura',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://smedia2.intoday.in/indiatoday/images/stories/2015JUNE/tempura_062415055231.jpg',
    duration: 20,
    ingredients: [
      '6 sheets sushi seaweed aka nori',
      '1 batch prepared sushi rice',
      '1/2 lb sushi-grade raw salmon or desired raw fish of choice',
      '4 oz cream cheese sliced into strips',
      '1 avocado sliced',
      'soy sauce for serving',
    ],
    instructions: [
      'Place the seaweed on a bamboo mat, then cover the sheet of seaweed with an even layer of prepared sushi rice. Smooth gently with the rice paddle.',
      'Layer salmon, cream cheese, and avocado on the rice, and roll it up tightly. Slice with a sharp knife, and enjoy with soy sauce.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c3',
    ],
    title: 'Gyoza ',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://smedia2.intoday.in/indiatoday/images/stories/2015JUNE/gyoza_062415055231.jpg',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm11',
    categories: [
      'c4',
    ],
    title: 'Aloo gobi ',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://images.ctfassets.net/3s5io6mnxfqz/1FRcejFvVGgWlqAu0nvVuI/c5db1084ea9431518e83c96a53212e1f/image1.jpg?fm=jpg&w=1200&fl=progressive',
    duration: 20,
    ingredients: [
      '6 sheets sushi seaweed aka nori',
      '1 batch prepared sushi rice',
      '1/2 lb sushi-grade raw salmon or desired raw fish of choice',
      '4 oz cream cheese sliced into strips',
      '1 avocado sliced',
      'soy sauce for serving',
    ],
    instructions: [
      'Place the seaweed on a bamboo mat, then cover the sheet of seaweed with an even layer of prepared sushi rice. Smooth gently with the rice paddle.',
      'Layer salmon, cream cheese, and avocado on the rice, and roll it up tightly. Slice with a sharp knife, and enjoy with soy sauce.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm12',
    categories: [
      'c4',
    ],
    title: 'Palak Paneer. ',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.ctfassets.net/3s5io6mnxfqz/yeg6ybqetjvexIWUWiCuy/9e0ce6ef1df7fb407c4caf47aaff609a/image1.jpg?fm=jpg&w=1200&fl=progressive',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm13',
    categories: [
      'c4',
    ],
    title: 'Chana masala',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://images.ctfassets.net/3s5io6mnxfqz/1LrSzMcDPk11m2jISOSqkC/18e8c8e92626ddc557ce301117655d64/image2.jpg?fm=jpg&w=1200&fl=progressive',
    duration: 20,
    ingredients: [
      '6 sheets sushi seaweed aka nori',
      '1 batch prepared sushi rice',
      '1/2 lb sushi-grade raw salmon or desired raw fish of choice',
      '4 oz cream cheese sliced into strips',
      '1 avocado sliced',
      'soy sauce for serving',
    ],
    instructions: [
      'Place the seaweed on a bamboo mat, then cover the sheet of seaweed with an even layer of prepared sushi rice. Smooth gently with the rice paddle.',
      'Layer salmon, cream cheese, and avocado on the rice, and roll it up tightly. Slice with a sharp knife, and enjoy with soy sauce.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm14',
    categories: [
      'c4',
    ],
    title: 'Doughy, butter-brushed naan ',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.ctfassets.net/3s5io6mnxfqz/463XQvQwEDL9ZgKJpP1nZ4/84e387414b62ac0e4ee9bd02e5b19045/image1.jpg?fm=jpg&w=1200&fl=progressive',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm15',
    categories: [
      'c5',
    ],
    title: 'Eggplant Rollatini',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://www.tasteofhome.com/wp-content/uploads/2018/01/Eggplant-Rollatini_EXPS_THCA19_41566_B08_07_1b-6.jpg?resize=696,696',
    duration: 20,
    ingredients: [
      '6 sheets sushi seaweed aka nori',
      '1 batch prepared sushi rice',
      '1/2 lb sushi-grade raw salmon or desired raw fish of choice',
      '4 oz cream cheese sliced into strips',
      '1 avocado sliced',
      'soy sauce for serving',
    ],
    instructions: [
      'Place the seaweed on a bamboo mat, then cover the sheet of seaweed with an even layer of prepared sushi rice. Smooth gently with the rice paddle.',
      'Layer salmon, cream cheese, and avocado on the rice, and roll it up tightly. Slice with a sharp knife, and enjoy with soy sauce.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm16',
    categories: [
      'c5',
    ],
    title: 'Cherry Tomato & Basil Focaccia',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://www.tasteofhome.com/wp-content/uploads/2018/01/exps152109_THCA163696D08_27_2b-3.jpg?resize=700,700',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm15',
    categories: [
      'c5',
    ],
    title: 'Eggplant Rollatini',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
    'https://www.tasteofhome.com/wp-content/uploads/2018/01/Eggplant-Rollatini_EXPS_THCA19_41566_B08_07_1b-6.jpg?resize=696,696',
    duration: 20,
    ingredients: [
      '6 sheets sushi seaweed aka nori',
      '1 batch prepared sushi rice',
      '1/2 lb sushi-grade raw salmon or desired raw fish of choice',
      '4 oz cream cheese sliced into strips',
      '1 avocado sliced',
      'soy sauce for serving',
    ],
    instructions: [
      'Place the seaweed on a bamboo mat, then cover the sheet of seaweed with an even layer of prepared sushi rice. Smooth gently with the rice paddle.',
      'Layer salmon, cream cheese, and avocado on the rice, and roll it up tightly. Slice with a sharp knife, and enjoy with soy sauce.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm16',
    categories: [
      'c5',
    ],
    title: 'Cherry Tomato & Basil Focaccia',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://www.tasteofhome.com/wp-content/uploads/2018/01/exps152109_THCA163696D08_27_2b-3.jpg?resize=700,700',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm17',
    categories: [
      'c6',
    ],
    title: 'Taramasalata',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/taramasalata-401c253.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm18',
    categories: [
      'c6',
    ],
    title: 'Honey & baklava',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/baklava-6dc5679.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm17',
    categories: [
      'c6',
    ],
    title: 'Taramasalata',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/taramasalata-401c253.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm18',
    categories: [
      'c6',
    ],
    title: 'Honey & baklava',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/baklava-6dc5679.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm19',
    categories: [
      'c7',
    ],
    title: 'Gazpacho',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/salmorejo-0aacf51.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm20',
    categories: [
      'c7',
    ],
    title: 'Tortilla Española',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/tortilla-6ff8c86.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm19',
    categories: [
      'c7',
    ],
    title: 'Gazpacho',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/salmorejo-0aacf51.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm20',
    categories: [
      'c7',
    ],
    title: 'Tortilla Española',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/tortilla-6ff8c86.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm21',
    categories: [
      'c8',
    ],
    title: 'Moroccan Vegetable Tagine ',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://www.themediterraneandish.com/wp-content/uploads/2017/11/Moroccan-Vegtable-Tagine-Recipe-The-Mediterranean-Dish-3.jpg',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm22',
    categories: [
      'c8',
    ],
    title: 'Sweet Potato Stew',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://www.themediterraneandish.com/wp-content/uploads/2020/01/Sweet-potato-stew-recipe-5.jpg',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm21',
    categories: [
      'c8',
    ],
    title: 'Moroccan Vegetable Tagine ',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://www.themediterraneandish.com/wp-content/uploads/2017/11/Moroccan-Vegtable-Tagine-Recipe-The-Mediterranean-Dish-3.jpg',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm22',
    categories: [
      'c8',
    ],
    title: 'Sweet Potato Stew',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://www.themediterraneandish.com/wp-content/uploads/2020/01/Sweet-potato-stew-recipe-5.jpg',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm23',
    categories: [
      'c9',
    ],
    title: 'Tabbouleh – Parsley Bulgur Salad ',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://nomadparadise.com/wp-content/uploads/2020/08/lebanese-food-1-768x512.jpg.webp',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm24',
    categories: [
      'c9',
    ],
    title: 'Fattoush – Pita Salad',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://nomadparadise.com/wp-content/uploads/2020/08/lebanese-food-2-768x512.jpg.webp',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm23',
    categories: [
      'c9',
    ],
    title: 'Tabbouleh – Parsley Bulgur Salad ',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://nomadparadise.com/wp-content/uploads/2020/08/lebanese-food-1-768x512.jpg.webp',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm24',
    categories: [
      'c9',
    ],
    title: 'Fattoush – Pita Salad',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://nomadparadise.com/wp-content/uploads/2020/08/lebanese-food-2-768x512.jpg.webp',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm25',
    categories: [
      'c10',
    ],
    title: 'B’ssara',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/fava_bean_soup-8f6c140.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm26',
    categories: [
      'c10',
    ],
    title: 'B’stilla',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/pie-4cb9bce.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm24',
    categories: [
      'c9',
    ],
    title: 'Fattoush – Pita Salad',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://nomadparadise.com/wp-content/uploads/2020/08/lebanese-food-2-768x512.jpg.webp',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm25',
    categories: [
      'c10',
    ],
    title: 'B’ssara',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/fava_bean_soup-8f6c140.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',

    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm26',
    categories: [
      'c10',
    ],
    title: 'B’stilla',
    affordability: Affordability.LittleBitPricey,
    complexity: Complexity.Challenging,
    imageUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/pie-4cb9bce.jpg?quality=90&webp=true&resize=700,350',
    duration: 35,
    ingredients: [
      ' 2/5 cup soy sauce',
      ' 1/2 cup water',
      ' 2 tablespoons mirin rice wine',
      ' 2 tablespoons rice vinegar',
      ' 2/5 cup light brown sugar',
      ' 1 teaspoon ginger, minced',
      ' 1 clove garlic, minced',
      ' 5 teaspoons cornstarch',
      ' 2 pounds chicken thighs, boneless, skinless, cut into 1” by 1 ¼” pieces',
      ' 8 bamboo skewers, or metal skewers',
      ' kosher salt, as needed for seasoing',
      ' black pepper, as needed for seasoning',
      ' 2 tablspoons vegetable oil',
      ' 1 teaspoon sesame seeds',
    ],
    instructions: [
      'In a medium-size pot whisk together soy sauce, water, mirin, rice vinegar, sugar, ginger, garlic, and cornstarch.',
      'Bring mixture to a boil, constantly whisk until sauce is slightly thickened, about 1 minute.',
      'Transfer 1 cup of the sauce to a bowl to use for basting the chicken.',
      'Thread cut pieces of chicken on wooden skewers that have been soaked in water for 30 minutes. Season with salt and pepper on both sides.',
      'Drizzle both sides of skewers with a small amount of oil to prevent sticking when cooking.',
      'Preheat grill over medium-high heat. Use a paper towel dipped in oil to clean and grease the grill grates.',
      'Once the grill is hot add the skewers and cook for 4 minutes. Flip over and baste the cooked side with the sauce. Cook 4 minutes.',
      'Flip skewer over, baste with sauce, cook 2 minutes covered.',
      'Flip skewer over again, baste, cook 2 minutes covered.',
      'Repeat flipping, basting and covered cooking 2 additional times, 16 minutes total cooking time.',
      'Sprinkle chicken yakitori skewers with sesame seeds. Serve immediately with additional sauce.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
];
